---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    target-branch: "master"
    labels:
      - "github-actions"
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    target-branch: "master"
    labels:
      - "nuget"
      - "dependencies"