---
name: ci

env:
  PROJECT_NAME: UnityNuGet

on:
  push:
    paths-ignore:
      - doc/**
      - img/**
      - changelog.md
      - readme.md
  pull_request:
    paths-ignore:
      - doc/**
      - img/**
      - changelog.md
      - readme.md

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build & test (Release)
        run: dotnet test src -c Release --logger "console;verbosity=normal"

      - name: Should Deploy?
        if: github.event_name == 'push'
        run: |
          if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+" ) {
              echo "UNITYNUGET_DEPLOY=1" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          }  

      - name: Publish (Release)
        if: env.UNITYNUGET_DEPLOY == 1
        run: dotnet publish src/UnityNuGet.Server/UnityNuGet.Server.csproj -c Release -o build/${{env.PROJECT_NAME}}

      - name: Azure Deploy
        if: env.UNITYNUGET_DEPLOY == 1
        uses: azure/webapps-deploy@v3
        with:
          app-name: unitynuget-registry
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build/${{env.PROJECT_NAME}}
